### PR TITLE
Speed up float parsing

### LINKED ISSUE #108: Parsing floats is slow
These two lines are extremely expensive:

selection_003

We can entirely avoid the division and multiplication by using a lookup table, or some other better approach.

### LINKED ISSUE #109: Long integer causes the following byte to be lost
```rust
serde_json::from_str::<Vec<f64>>("[123456789012345678901]").unwrap();
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Syntax("EOF while parsing a list", 1, 23)'
```

Here is the buggy code: [json/src/de.rs#L294-L302](https://github.com/serde-rs/json/blob/e059d03aea557bbd2c53ff5af18951c65da8f509/json/src/de.rs#L294-L302). The first one needs to be a peek.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #108 and fixes #109.

Parse floats as a u64 until the end, then use a lookup table to scale by the correct power of 10. This is faster and also more accurate. The old code used repeated division by 10 which is so inaccurate that `1.0 / 10.0 / 10.0 / 10.0 / 10.0 / 10.0 / 10.0 != 1e-6`.

This is about 40% improvement on the [Canada benchmark](https://github.com/serde-rs/json-benchmark) (almost twice as fast).

### CODE REVIEW

File: json/src/de.rs [hunk 1]
```diff
@@ -404,35 +394,60 @@ impl<R: Read> DeserializerImpl<R> {
...
+            Some(pow) => {
+                if exponent >= 0 {
+                    significand as f64 * pow
+                } else {
+                    significand as f64 / pow
+                }
+            }
+            None => {
+                if exponent >= 0 && significand != 0 {
+                    f64::INFINITY
```
Comment (oli-obk) [inline json/src/de.rs]: I don't think we should default to infinity. Not only does it break round tripping, it's also very confusing to get an infinity from a non-infinite number

File: json/src/de.rs [hunk 2]
```diff
@@ -404,35 +394,60 @@ impl<R: Read> DeserializerImpl<R> {
...
+            c @ b'0' ... b'9' => { (c - b'0') as i32 }
             _ => { return Err(self.error(ErrorCode::InvalidNumber)); }
         };
 
         while let c @ b'0' ... b'9' = try!(self.peek_or_null()) {
             self.eat_char();
+            let digit = (c - b'0') as i32;
+
+            if overflow!(exp * 10 + digit, i32::MAX) {
+                // Really big exponent, just ignore the rest.
```
Comment (oli-obk) [inline json/src/de.rs]: as with the other overflowing cases above, shouldn't we just bail out?

File: json/src/de.rs (hunk 1 above)
Comment (dtolnay) [inline json/src/de.rs]: This matches the current behavior (as of 0.7.4). I filed #112 to change the behavior.

```rust
assert_eq!(f64::INFINITY, serde_json::from_str("1e1000").unwrap());
```

File: json_tests/tests/test_json.rs [hunk 3]
```diff
@@ -750,11 +750,14 @@ fn test_parse_number_errors() {
         (".", Error::Syntax(ErrorCode::ExpectedSomeValue, 1, 1)),
         ("-", Error::Syntax(ErrorCode::InvalidNumber, 1, 1)),
         ("00", Error::Syntax(ErrorCode::InvalidNumber, 1, 2)),
+        ("0x80", Error::Syntax(ErrorCode::TrailingCharacters, 1, 2)),
```
Comment (oli-obk) [inline json_tests/tests/test_json.rs]: did those new tests fail before these changes? Or are they new failures

Comment (dtolnay) [inline json_tests/tests/test_json.rs]: These failed before but were not tested.
